FROM nvcr.io/nvidia/l4t-jetpack:r36.4.0

WORKDIR /app

RUN apt-get update && apt-get install -y \
    python3-pip \
    python3-dev \
    python3-opencv \
    gstreamer1.0-tools \
    v4l-utils \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/requirements.txt
RUN pip3 install --no-cache-dir -r /app/requirements.txt

COPY app /app/app
COPY models /app/models

CMD ["python3", "/app/app/main.py"]
