FROM nvcr.io/nvidia/pytorch:25.03-py3-igpu

RUN pip uninstall -y opencv-python opencv-python-headless || true

RUN apt-get update && apt-get install -y \
    build-essential cmake git pkg-config \
    libjpeg-dev libtiff-dev libpng-dev \
    libavcodec-dev libavformat-dev libswscale-dev \
    libv4l-dev libxvidcore-dev libx264-dev \
    libgtk-3-dev libatlas-base-dev gfortran \
    python3-dev python3-numpy \
    libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
    python3-opencv \
    && rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --no-deps ultralytics
RUN python3 -m pip install Jetson.GPIO pillow pyyaml requests scipy matplotlib psutil py-cpuinfo pandas tqdm

WORKDIR /workspace
COPY app/main.py /workspace/app/main.py

CMD ["python3", "-u", "/workspace/app/main.py"]