FROM nvcr.io/nvidia/pytorch:25.05-py3-igpu

WORKDIR /app

RUN apt-get update && apt-get install -y \
    python3-pip \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender1 \
    gstreamer1.0-tools \
    v4l-utils \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/requirements.txt
RUN pip3 install --no-cache-dir -r /app/requirements.txt

COPY app /app/app
COPY models /app/models

CMD ["python3", "/app/app/main.py"]