name: Test Suite

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
        - completed

jobs:
  Test_Suite:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download test info
        uses: actions/download-artifact@v4
        if: (${{ github.event_name == 'workflow_run' }} && ${{ github.event.workflow_run.conclusion == 'success' }}) || ${{ github.event_name != 'workflow_run' }}
        with:
          name: testinfo
      - name: Trigger Test Suite github action
        run: |
          if [[ ${{ github.event_name == 'release' }} == true ]]; then
            CTVER=${{ github.event.release.tag_name }}
          elif [[ ${{ github.event_name == 'workflow_run' }} == true ]]; then
            CTVER=$(cat testinfo.txt | grep CTVER | cut -d'=' -f2)
          else
            CTVER="latest"
          fi
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TESTSUITE_REPOSITORY_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/ICICLE-ai/ml_workbench_test_suite/dispatches \
            -d '{"event_type":"dispatch-event", "client_payload": {"ct_version": "$CTVER"}}'
