name: Test Suite

on:
  release:
    types: [released]
  push:
    branches:
      - dev
      - test_suite_integration

jobs:
  Test_Suite:
    runs-on: ubuntu-latest
    steps:
      - name: Upgrade curl
        run: sudo apt-get install --only-upgrade curl
      - name: Get repo information
        run: |
          curl -L --retry 5 --retry-delay 10 --tlsv1.2 --http1.1 -v \
            -H "Accept: application/vnd.github+json" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.TESTSUITE_REPOSITORY_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/ICICLE-ai/ml_workbench_test_suite
      - name: Trigger Test Suite github action
        run: |
          curl -L --retry 5 --retry-delay 10 --tlsv1.3 --http1.1 -v \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.TESTSUITE_REPOSITORY_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/ICICLE-ai/ml_workbench_test_suite/dispatches \
            -d '{"event_type": "dispatch-event", "client_payload": {}}'
