name: Test Suite

on:
  release:
    types: [released]
  push:
    branches:
      - dev
      - test_suite_integration

jobs:
  Test_Suite:
    runs-on: ubuntu-latest
    steps:
      - name: Upgrade to latest curl
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev
          LATEST_TAG=$(curl -s https://api.github.com/repos/curl/curl/releases/latest | jq -r .name)
          curl -LO "https://curl.se/download/curl-${LATEST_TAG}.tar.gz"
          tar -xvf "curl-${LATEST_TAG}.tar.gz"
          cd "curl-${LATEST_TAG}"
          ./configure --with-openssl  --without-libpsl
          make
          sudo make install
          curl --version
      - name: Get repo information
        run: |
          curl -L --retry 5 --retry-delay 10 --tlsv1.2 --http1.1 -v \
            -H "Accept: application/vnd.github+json" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.TESTSUITE_REPOSITORY_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/ICICLE-ai/ml_workbench_test_suite
      - name: Trigger Test Suite github action
        run: |
          curl -L --retry 5 --retry-delay 10 --tlsv1.3 --http1.1 -v -i \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.TESTSUITE_REPOSITORY_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/ICICLE-ai/ml_workbench_test_suite/dispatches \
            -d '{"event_type": "dispatch-event", "client_payload": {}}'
